import { defineConfig, devices } from '@playwright/test'

// Offline/PWA verification only - see CLAUDE.md's acceptance checks:
// "Turn the network off: the app loads, every screen works, every write
// persists." This needs a real production build (the service worker is
// generated by vite-plugin-pwa at build time) served over HTTP, not the dev
// server - a service worker will not install from vite dev's unbundled
// output the way it installs from `dist`.
export default defineConfig({
  testDir: './e2e',
  fullyParallel: false,
  retries: 0,
  reporter: 'list',
  use: {
    baseURL: 'http://localhost:4173',
    trace: 'retain-on-failure',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: {
    command: 'npm run build && npm run preview -- --port 4173 --strictPort',
    url: 'http://localhost:4173',
    reuseExistingServer: false,
    timeout: 120_000,
  },
})
