import { defineConfig, devices } from '@playwright/test'

// Offline/PWA verification only - see CLAUDE.md's acceptance checks:
// "Turn the network off: the app loads, every screen works, every write
// persists." This needs a real production build (the service worker is
// generated by vite-plugin-pwa at build time) served over HTTP, not the dev
// server - a service worker will not install from vite dev's unbundled
// output the way it installs from `dist`.
//
// PLAYWRIGHT_BASE_URL points this at a real deployment (e.g. Netlify) instead
// of a local preview server - set it and the local build/serve step is
// skipped entirely, so a run against a remote URL cannot silently fall back
// to testing localhost instead.
const remoteBaseURL = process.env.PLAYWRIGHT_BASE_URL

export default defineConfig({
  testDir: './e2e',
  fullyParallel: false,
  retries: 0,
  reporter: 'list',
  use: {
    baseURL: remoteBaseURL ?? 'http://localhost:4173',
    trace: 'retain-on-failure',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: remoteBaseURL
    ? undefined
    : {
        command: 'npm run build && npm run preview -- --port 4173 --strictPort',
        url: 'http://localhost:4173',
        reuseExistingServer: false,
        timeout: 120_000,
      },
})
